hobbies:
  - id: "gardening"
    icon: "🌺"
    name: "Gardening"
    effects:
      happiness:
        value: 2
        duration: 3600
      stress:
        value: -1
        duration: 3600
  - id: "reading"
    icon: "📚"
    name: "Reading"
    effects:
      intelligence:
        value: 1
        duration: 7200
      creativity:
        value: 2
        duration: 7200

needs:
  - "food"
  - "water"
  - "shelter"
  - "social"

perks:
  - "fast_learner"
  - "creative_mind"
  - "green_thumb"

buffs:
  - "well_rested"
  - "inspired"
  - "focused"