- ID: "residential_district"
  Name: "Green Valley District"
  ControlledBy: "city_council"
  Zones:
    - "residential_1"
    - "public_1"

- ID: "business_district"
  Name: "Commerce Square District"
  ControlledBy: "merchant_guild"
  Zones:
    - "commercial_1"
    - "industrial_1"

- ID: "expansion_zone"
  Name: "New Development Area"
  ControlledBy: null
  Zones: []