- ID: "residential_1"
  Name: "Peaceful Grove"
  Type: "house"
  InitialBusinessID: "home_garden"
  X: 100.0
  Y: 100.0
  Width: 50.0
  Height: 50.0

- ID: "commercial_1"
  Name: "Market Square"
  Type: "shop"
  InitialBusinessID: "general_store"
  X: 200.0
  Y: 100.0
  Width: 75.0
  Height: 60.0

- ID: "industrial_1"
  Name: "Factory District"
  Type: "factory"
  InitialBusinessID: "manufacturing_plant"
  X: 300.0
  Y: 200.0
  Width: 100.0
  Height: 80.0

- ID: "public_1"
  Name: "Central Park"
  Type: "park"
  InitialBusinessID: "park_services"
  X: 150.0
  Y: 150.0
  Width: 120.0
  Height: 120.0