- id: "zone_1"
  name: "Market District"
  type: "shop"
  x: 100
  y: 100
  width: 200
  height: 150
  player_ids: []

- id: "zone_2"
  name: "Residential Area"
  type: "house"
  x: 350
  y: 100
  width: 180
  height: 160
  player_ids: []

- id: "zone_3"
  name: "Industrial Complex"
  type: "factory"
  x: 600
  y: 100
  width: 250
  height: 200
  player_ids: []

- id: "zone_4"
  name: "Central Park"
  type: "park"
  x: 350
  y: 300
  width: 200
  height: 200
  player_ids: []